INSERT INTO genre (genre_name) VALUES ('Classical');
INSERT INTO genre (genre_name) VALUES ('Country');
INSERT INTO genre (genre_name) VALUES ('EDM');
INSERT INTO genre (genre_name) VALUES ('Rap');
INSERT INTO genre (genre_name) VALUES ('Indie Rock');
INSERT INTO genre (genre_name) VALUES ('Jazz');
INSERT INTO genre (genre_name) VALUES ('K-Pop');
INSERT INTO genre (genre_name) VALUES ('Metal');
INSERT INTO genre (genre_name) VALUES ('Pop');
INSERT INTO genre (genre_name) VALUES ('R&B');
INSERT INTO genre (genre_name) VALUES ('Rock');
INSERT INTO genre (genre_name) VALUES ('Blues');
INSERT INTO genre (genre_name) VALUES ('Amapiano');
INSERT INTO genre (genre_name) VALUES ('Afrobeat');
INSERT INTO genre (genre_name) VALUES ('Parody');
INSERT INTO genre (genre_name) VALUES ('Vaporwave');
INSERT INTO genre (genre_name) VALUES ('Soul');
INSERT INTO genre (genre_name) VALUES ('Alternative');
INSERT INTO genre (genre_name) VALUES ('Disco');
INSERT INTO genre (genre_name) VALUES ('Punk');

INSERT INTO artist (artist_name, intial_formation, artist_rating, notes, active) VALUES ('David Bowie', '1962', '5', 'David Bowie from the sets of Twin Peaks: Fire Walk With Me to the red plains of Mars, they are excellent all around', 'false');
